/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sites: Site;
    media: Media;
    pages: Page;
    forms: Form;
    'form-submissions': FormSubmission;
    services: Service;
    'student-cases': StudentCase;
    'marketing-pages': MarketingPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'student-cases': StudentCasesSelect<false> | StudentCasesSelect<true>;
    'marketing-pages': MarketingPagesSelect<false> | MarketingPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'platform-settings': PlatformSetting;
  };
  globalsSelect: {
    'platform-settings': PlatformSettingsSelect<false> | PlatformSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name used in the admin account UI.
   */
  fullName?: string | null;
  avatar?: (number | null) | Media;
  timezone?: string | null;
  language?: ('en' | 'ar') | null;
  role: 'super-admin' | 'client';
  /**
   * The site this user belongs to.
   */
  siteId?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Friendly label shown when selecting this media in the admin picker.
   */
  title?: string | null;
  caption?: string | null;
  /**
   * Site context is assigned automatically in normal workflows.
   */
  siteId?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  siteName: string;
  /**
   * Stable site key used for permissions and content scoping.
   */
  siteId: string;
  siteDescription?: string | null;
  /**
   * Primary domain, for example acme.com or acme.localhost.
   */
  domain?: string | null;
  /**
   * Optional short subdomain used for matching preview hosts.
   */
  subdomain?: string | null;
  status: 'active' | 'draft' | 'maintenance';
  defaultLanguage?: string | null;
  /**
   * IANA timezone string such as Europe/Paris or America/New_York.
   */
  timezone?: string | null;
  /**
   * The client user who manages this site. Only client-role users are shown.
   */
  owner?: (number | null) | User;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  fontFamily?: ('inter' | 'geist' | 'poppins' | 'outfit' | 'plus-jakarta-sans' | 'dm-sans') | null;
  headerNav?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  showSiteTitle?: boolean | null;
  showLanguageSwitcher?: boolean | null;
  showThemeToggle?: boolean | null;
  stickyHeader?: boolean | null;
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  showNewsletterSignup?: boolean | null;
  footerTagline?: string | null;
  footerNote?: string | null;
  copyrightText?: string | null;
  footerShowCtaBanner?: boolean | null;
  footerCtaHeading?: string | null;
  footerCtaDescription?: string | null;
  footerCtaButtonLabel?: string | null;
  footerCtaButtonUrl?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  ogImage?: (number | null) | Media;
  twitterImage?: (number | null) | Media;
  allowIndexing?: boolean | null;
  publicEmail?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  address?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Primary page title shown in admin and page headers.
   */
  title: string;
  /**
   * URL path without leading slash, e.g. "about" not "/about". Unique per site.
   */
  slug: string;
  status: 'draft' | 'published';
  pageType?: ('landing' | 'blog' | 'about' | 'contact' | 'custom') | null;
  template?: ('default' | 'full-width' | 'sidebar-left' | 'sidebar-right') | null;
  parentPage?: (number | null) | Page;
  pageName?: string | null;
  shortDescription?: string | null;
  author?: string | null;
  branding?: {
    logoUrl?: string | null;
    faviconUrl?: string | null;
    headerVariant?: ('default' | 'centered' | 'minimal' | 'transparent' | 'editorial') | null;
    footerVariant?: ('default' | 'centered' | 'minimal' | 'columns' | 'editorial') | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    robotsIndex?: boolean | null;
    image?: (number | null) | Media;
    twitterImage?: (number | null) | Media;
  };
  publishDate?: string | null;
  visibility?: ('public' | 'private' | 'password-protected') | null;
  blocks?:
    | (
        | {
            style?: ('gradient' | 'minimal' | 'split') | null;
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            style?: ('cards' | 'list' | 'minimal') | null;
            heading?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  /**
                   * Icon name or identifier
                   */
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            description?: string | null;
            buttonLabel: string;
            buttonLink: string;
            style?: ('default' | 'centered' | 'withBackground') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            style?: ('default' | 'split') | null;
            form: number | Form;
            heading?: string | null;
            description?: string | null;
            leftPanelHeading?: string | null;
            leftPanelDescription?: string | null;
            contactItems?:
              | {
                  icon?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            submitLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            image: number | Media;
            primaryCtaLabel?: string | null;
            primaryCtaLink?: string | null;
            secondaryCtaLabel?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroWithImage';
          }
        | {
            mode?: ('manual' | 'dynamic') | null;
            style?: ('cards' | 'list') | null;
            heading?: string | null;
            subheading?: string | null;
            /**
             * Max services to display in dynamic mode.
             */
            limit?: number | null;
            services?:
              | {
                  title: string;
                  description?: string | null;
                  /**
                   * Icon name or emoji
                   */
                  icon?: string | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesCards';
          }
        | {
            style?: ('default' | 'alt' | 'timeline' | 'cards') | null;
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Legacy field kept for older content. Use Section Description for new pages.
             */
            subheading?: string | null;
            steps?:
              | {
                  stepLabel?: string | null;
                  title: string;
                  /**
                   * Optional emoji or icon label for the step badge.
                   */
                  icon?: string | null;
                  description?: string | null;
                  /**
                   * Optional label shown instead of the auto step number.
                   */
                  numberOverride?: string | null;
                  isHighlighted?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsTimeline';
          }
        | {
            style?: ('dark' | 'light' | 'branded') | null;
            heading?: string | null;
            stats?:
              | {
                  /**
                   * e.g. "99%", "10k+", "$2M"
                   */
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            style?: ('cards' | 'single' | 'minimal' | 'featured') | null;
            heading?: string | null;
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  image: number | Media;
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloud';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            plans?:
              | {
                  name: string;
                  /**
                   * e.g. "$29/mo" or "Free"
                   */
                  price: string;
                  description?: string | null;
                  /**
                   * One feature per line
                   */
                  features?: string | null;
                  ctaLabel?: string | null;
                  ctaLink?: string | null;
                  highlighted?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingTable';
          }
        | {
            style?: ('accordion' | 'grid' | 'sidebar') | null;
            heading?: string | null;
            /**
             * Shown in the sidebar panel alongside the heading.
             */
            description?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Highlighted emphasis word shown inline in heading.
             */
            highlightedWord?: string | null;
            subheading?: string | null;
            badgeLabel?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaLink?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaLink?: string | null;
            stats?:
              | {
                  /**
                   * e.g. "98%", "15K+"
                   */
                  value: string;
                  label: string;
                  color?: ('blue' | 'green' | 'purple' | 'amber') | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            mainImage?: (number | null) | Media;
            sideImages?:
              | {
                  image?: (number | null) | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            topOverlayCard?: {
              cardLabel?: string | null;
              cardText?: string | null;
            };
            bottomOverlayCard?: {
              cardLabel?: string | null;
              itemTitle?: string | null;
              itemDescription?: string | null;
            };
            featureHighlights?:
              | {
                  /**
                   * Emoji or icon name
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroEditorial';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            items?:
              | {
                  /**
                   * Emoji or icon name
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * e.g. "POPULAR", "NEW"
                   */
                  badge?: string | null;
                  ctaLabel?: string | null;
                  ctaLink?: string | null;
                  image?: (number | null) | Media;
                  isFeatured?: boolean | null;
                  theme?: ('light' | 'dark') | null;
                  iconStyle?: ('primarySoft' | 'secondarySoft' | 'surfaceHigh' | 'darkGlass') | null;
                  details?:
                    | {
                        detail: string;
                        id?: string | null;
                      }[]
                    | null;
                  tags?:
                    | {
                        tag: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesBento';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            theme?: ('light' | 'brand') | null;
            imagePosition?: ('left' | 'right') | null;
            calloutText?: string | null;
            showSkewAccent?: boolean | null;
            features?:
              | {
                  /**
                   * Emoji or icon name
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitContent';
          }
      )[]
    | null;
  /**
   * Site context is assigned automatically in normal workflows.
   */
  siteId?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | {
        label: string;
        /**
         * Machine-friendly field name (e.g. "first_name")
         */
        name: string;
        type: 'text' | 'email' | 'textarea' | 'select' | 'file';
        required?: boolean | null;
        options?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  confirmationMessage?: string | null;
  /**
   * Site context is assigned automatically in normal workflows.
   */
  siteId?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  /**
   * Submitted form data
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Site context is assigned automatically in normal workflows.
   */
  siteId?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Unique per site.
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  /**
   * Site context is assigned automatically in normal workflows.
   */
  siteId?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-cases".
 */
export interface StudentCase {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  nationality?: string | null;
  dateOfBirth?: string | null;
  currentStage: 'lead' | 'consultation' | 'application' | 'visa' | 'enrolled';
  status: 'new' | 'in-progress' | 'waiting-student' | 'waiting-institution' | 'completed' | 'closed-lost';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  assignedTo?: (number | null) | User;
  nextAction?: string | null;
  nextActionDate?: string | null;
  consultationOutcome?: string | null;
  targetCountry?: string | null;
  targetCity?: string | null;
  targetField?: string | null;
  educationLevel?: string | null;
  languageLevel?: string | null;
  visaType?: string | null;
  preferredStartDate?: string | null;
  tasks?:
    | {
        title: string;
        status?: ('todo' | 'in-progress' | 'done') | null;
        dueDate?: string | null;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        name: string;
        status?: ('pending' | 'received' | 'verified') | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        at: string;
        title: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  internalNotes?:
    | {
        note: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Linked form submission that created this case.
   */
  sourceSubmission?: (number | null) | FormSubmission;
  sourceChannel?: ('form' | 'manual' | 'import') | null;
  /**
   * Site context is assigned automatically in normal workflows.
   */
  siteId?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Platform marketing pages for monocms.app (super-admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-pages".
 */
export interface MarketingPage {
  id: number;
  title: string;
  /**
   * Leave empty string for homepage (/). Use "about", "pricing", "contact" etc.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Marks this as the root domain homepage (/)
   */
  isHome?: boolean | null;
  /**
   * Auto-set when first published
   */
  publishedAt?: string | null;
  meta?: {
    /**
     * Overrides page title in search results
     */
    title?: string | null;
    /**
     * Max 160 characters recommended
     */
    description?: string | null;
    /**
     * Open Graph / social sharing image (1200×630px recommended)
     */
    ogImage?: (number | null) | Media;
  };
  blocks?:
    | (
        | {
            style?: ('gradient' | 'minimal' | 'split') | null;
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            image: number | Media;
            primaryCtaLabel?: string | null;
            primaryCtaLink?: string | null;
            secondaryCtaLabel?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroWithImage';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            /**
             * Highlighted emphasis word shown inline in heading.
             */
            highlightedWord?: string | null;
            subheading?: string | null;
            badgeLabel?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaLink?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaLink?: string | null;
            stats?:
              | {
                  /**
                   * e.g. "98%", "15K+"
                   */
                  value: string;
                  label: string;
                  color?: ('blue' | 'green' | 'purple' | 'amber') | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            mainImage?: (number | null) | Media;
            sideImages?:
              | {
                  image?: (number | null) | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            topOverlayCard?: {
              cardLabel?: string | null;
              cardText?: string | null;
            };
            bottomOverlayCard?: {
              cardLabel?: string | null;
              itemTitle?: string | null;
              itemDescription?: string | null;
            };
            featureHighlights?:
              | {
                  /**
                   * Emoji or icon name
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroEditorial';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            style?: ('cards' | 'list' | 'minimal') | null;
            heading?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  /**
                   * Icon name or identifier
                   */
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            mode?: ('manual' | 'dynamic') | null;
            style?: ('cards' | 'list') | null;
            heading?: string | null;
            subheading?: string | null;
            /**
             * Max services to display in dynamic mode.
             */
            limit?: number | null;
            services?:
              | {
                  title: string;
                  description?: string | null;
                  /**
                   * Icon name or emoji
                   */
                  icon?: string | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesCards';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            items?:
              | {
                  /**
                   * Emoji or icon name
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * e.g. "POPULAR", "NEW"
                   */
                  badge?: string | null;
                  ctaLabel?: string | null;
                  ctaLink?: string | null;
                  image?: (number | null) | Media;
                  isFeatured?: boolean | null;
                  theme?: ('light' | 'dark') | null;
                  iconStyle?: ('primarySoft' | 'secondarySoft' | 'surfaceHigh' | 'darkGlass') | null;
                  details?:
                    | {
                        detail: string;
                        id?: string | null;
                      }[]
                    | null;
                  tags?:
                    | {
                        tag: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesBento';
          }
        | {
            style?: ('default' | 'alt' | 'timeline' | 'cards') | null;
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Legacy field kept for older content. Use Section Description for new pages.
             */
            subheading?: string | null;
            steps?:
              | {
                  stepLabel?: string | null;
                  title: string;
                  /**
                   * Optional emoji or icon label for the step badge.
                   */
                  icon?: string | null;
                  description?: string | null;
                  /**
                   * Optional label shown instead of the auto step number.
                   */
                  numberOverride?: string | null;
                  isHighlighted?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsTimeline';
          }
        | {
            style?: ('dark' | 'light' | 'branded') | null;
            heading?: string | null;
            stats?:
              | {
                  /**
                   * e.g. "99%", "10k+", "$2M"
                   */
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            style?: ('cards' | 'single' | 'minimal' | 'featured') | null;
            heading?: string | null;
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  image: number | Media;
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloud';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            plans?:
              | {
                  name: string;
                  /**
                   * e.g. "$29/mo" or "Free"
                   */
                  price: string;
                  description?: string | null;
                  /**
                   * One feature per line
                   */
                  features?: string | null;
                  ctaLabel?: string | null;
                  ctaLink?: string | null;
                  highlighted?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingTable';
          }
        | {
            style?: ('accordion' | 'grid' | 'sidebar') | null;
            heading?: string | null;
            /**
             * Shown in the sidebar panel alongside the heading.
             */
            description?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            style?: ('default' | 'split') | null;
            form: number | Form;
            heading?: string | null;
            description?: string | null;
            leftPanelHeading?: string | null;
            leftPanelDescription?: string | null;
            contactItems?:
              | {
                  icon?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            submitLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
        | {
            heading: string;
            description?: string | null;
            buttonLabel: string;
            buttonLink: string;
            style?: ('default' | 'centered' | 'withBackground') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            theme?: ('light' | 'brand') | null;
            imagePosition?: ('left' | 'right') | null;
            calloutText?: string | null;
            showSkewAccent?: boolean | null;
            features?:
              | {
                  /**
                   * Emoji or icon name
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitContent';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'student-cases';
        value: number | StudentCase;
      } | null)
    | ({
        relationTo: 'marketing-pages';
        value: number | MarketingPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  avatar?: T;
  timezone?: T;
  language?: T;
  role?: T;
  siteId?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  siteName?: T;
  siteId?: T;
  siteDescription?: T;
  domain?: T;
  subdomain?: T;
  status?: T;
  defaultLanguage?: T;
  timezone?: T;
  owner?: T;
  logo?: T;
  favicon?: T;
  primaryColor?: T;
  secondaryColor?: T;
  fontFamily?: T;
  headerNav?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  showSiteTitle?: T;
  showLanguageSwitcher?: T;
  showThemeToggle?: T;
  stickyHeader?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  showNewsletterSignup?: T;
  footerTagline?: T;
  footerNote?: T;
  copyrightText?: T;
  footerShowCtaBanner?: T;
  footerCtaHeading?: T;
  footerCtaDescription?: T;
  footerCtaButtonLabel?: T;
  footerCtaButtonUrl?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  ogImage?: T;
  twitterImage?: T;
  allowIndexing?: T;
  publicEmail?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  caption?: T;
  siteId?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  pageType?: T;
  template?: T;
  parentPage?: T;
  pageName?: T;
  shortDescription?: T;
  author?: T;
  branding?:
    | T
    | {
        logoUrl?: T;
        faviconUrl?: T;
        headerVariant?: T;
        footerVariant?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        robotsIndex?: T;
        image?: T;
        twitterImage?: T;
      };
  publishDate?: T;
  visibility?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              style?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              style?: T;
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              buttonLink?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              style?: T;
              form?: T;
              heading?: T;
              description?: T;
              leftPanelHeading?: T;
              leftPanelDescription?: T;
              contactItems?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    id?: T;
                  };
              submitLabel?: T;
              id?: T;
              blockName?: T;
            };
        heroWithImage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              primaryCtaLabel?: T;
              primaryCtaLink?: T;
              secondaryCtaLabel?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        servicesCards?:
          | T
          | {
              mode?: T;
              style?: T;
              heading?: T;
              subheading?: T;
              limit?: T;
              services?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepsTimeline?:
          | T
          | {
              style?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              subheading?: T;
              steps?:
                | T
                | {
                    stepLabel?: T;
                    title?: T;
                    icon?: T;
                    description?: T;
                    numberOverride?: T;
                    isHighlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              style?: T;
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              style?: T;
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingTable?:
          | T
          | {
              heading?: T;
              subheading?: T;
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    features?: T;
                    ctaLabel?: T;
                    ctaLink?: T;
                    highlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              style?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroEditorial?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              highlightedWord?: T;
              subheading?: T;
              badgeLabel?: T;
              primaryCtaLabel?: T;
              primaryCtaLink?: T;
              secondaryCtaLabel?: T;
              secondaryCtaLink?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    color?: T;
                    description?: T;
                    id?: T;
                  };
              mainImage?: T;
              sideImages?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              topOverlayCard?:
                | T
                | {
                    cardLabel?: T;
                    cardText?: T;
                  };
              bottomOverlayCard?:
                | T
                | {
                    cardLabel?: T;
                    itemTitle?: T;
                    itemDescription?: T;
                  };
              featureHighlights?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesBento?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              ctaLabel?: T;
              ctaLink?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    badge?: T;
                    ctaLabel?: T;
                    ctaLink?: T;
                    image?: T;
                    isFeatured?: T;
                    theme?: T;
                    iconStyle?: T;
                    details?:
                      | T
                      | {
                          detail?: T;
                          id?: T;
                        };
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitContent?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              theme?: T;
              imagePosition?: T;
              calloutText?: T;
              showSkewAccent?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  siteId?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        label?: T;
        name?: T;
        type?: T;
        required?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  confirmationMessage?: T;
  siteId?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  data?: T;
  siteId?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  featuredImage?: T;
  siteId?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-cases_select".
 */
export interface StudentCasesSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  nationality?: T;
  dateOfBirth?: T;
  currentStage?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  nextAction?: T;
  nextActionDate?: T;
  consultationOutcome?: T;
  targetCountry?: T;
  targetCity?: T;
  targetField?: T;
  educationLevel?: T;
  languageLevel?: T;
  visaType?: T;
  preferredStartDate?: T;
  tasks?:
    | T
    | {
        title?: T;
        status?: T;
        dueDate?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        name?: T;
        status?: T;
        file?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        at?: T;
        title?: T;
        note?: T;
        id?: T;
      };
  internalNotes?:
    | T
    | {
        note?: T;
        createdAt?: T;
        id?: T;
      };
  sourceSubmission?: T;
  sourceChannel?: T;
  siteId?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-pages_select".
 */
export interface MarketingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  isHome?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              style?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        heroWithImage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              primaryCtaLabel?: T;
              primaryCtaLink?: T;
              secondaryCtaLabel?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        heroEditorial?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              highlightedWord?: T;
              subheading?: T;
              badgeLabel?: T;
              primaryCtaLabel?: T;
              primaryCtaLink?: T;
              secondaryCtaLabel?: T;
              secondaryCtaLink?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    color?: T;
                    description?: T;
                    id?: T;
                  };
              mainImage?: T;
              sideImages?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              topOverlayCard?:
                | T
                | {
                    cardLabel?: T;
                    cardText?: T;
                  };
              bottomOverlayCard?:
                | T
                | {
                    cardLabel?: T;
                    itemTitle?: T;
                    itemDescription?: T;
                  };
              featureHighlights?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              style?: T;
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesCards?:
          | T
          | {
              mode?: T;
              style?: T;
              heading?: T;
              subheading?: T;
              limit?: T;
              services?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesBento?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              ctaLabel?: T;
              ctaLink?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    badge?: T;
                    ctaLabel?: T;
                    ctaLink?: T;
                    image?: T;
                    isFeatured?: T;
                    theme?: T;
                    iconStyle?: T;
                    details?:
                      | T
                      | {
                          detail?: T;
                          id?: T;
                        };
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepsTimeline?:
          | T
          | {
              style?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              subheading?: T;
              steps?:
                | T
                | {
                    stepLabel?: T;
                    title?: T;
                    icon?: T;
                    description?: T;
                    numberOverride?: T;
                    isHighlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              style?: T;
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              style?: T;
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingTable?:
          | T
          | {
              heading?: T;
              subheading?: T;
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    features?: T;
                    ctaLabel?: T;
                    ctaLink?: T;
                    highlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              style?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              style?: T;
              form?: T;
              heading?: T;
              description?: T;
              leftPanelHeading?: T;
              leftPanelDescription?: T;
              contactItems?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    id?: T;
                  };
              submitLabel?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              buttonLink?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        splitContent?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              theme?: T;
              imagePosition?: T;
              calloutText?: T;
              showSkewAccent?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global settings for the monocms.app platform marketing site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings".
 */
export interface PlatformSetting {
  id: number;
  productName?: string | null;
  tagline?: string | null;
  /**
   * Primary logo (SVG or PNG, transparent bg)
   */
  logo?: (number | null) | Media;
  /**
   * Favicon (32×32 or 64×64 PNG)
   */
  favicon?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  navCta?: {
    label?: string | null;
    url?: string | null;
    variant?: ('primary' | 'ghost' | 'outline') | null;
  };
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Privacy Policy, Terms of Service, etc.
   */
  footerLegalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer copyright line. Use {year} as a placeholder for the current year.
   */
  copyrightText?: string | null;
  socialLinks?:
    | {
        platform: 'twitter' | 'linkedin' | 'github' | 'instagram' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used when a marketing page has no custom meta title.
   */
  defaultSeoTitle?: string | null;
  defaultSeoDescription?: string | null;
  /**
   * Fallback social sharing image (1200×630px)
   */
  ogImage?: (number | null) | Media;
  contactEmail?: string | null;
  /**
   * Optional banner shown at the top of the marketing site.
   */
  announcementBar?: {
    enabled?: boolean | null;
    variant?: ('info' | 'success' | 'warning') | null;
    message?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings_select".
 */
export interface PlatformSettingsSelect<T extends boolean = true> {
  productName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  navCta?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footerLegalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  ogImage?: T;
  contactEmail?: T;
  announcementBar?:
    | T
    | {
        enabled?: T;
        variant?: T;
        message?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}